apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: influxdb-restore
  namespace: argowf
spec:
  serviceAccountName: argo-workflow
  entrypoint: main
  arguments:
    parameters:
      - name: bucket
        value: poc-argo
      - name: bucket-path
        value: backup
  templates:
  - name: main
    steps:
    - - name: influx
        template: influxdb
    - - name: pull-backup
        template: pull-backup
    - - name: restore-backup
        template: restore-backup
        arguments:
          parameters:
            - name: ip
              value: '{{steps.influx.ip}}'
          artifacts:
            - name: data
              from: "{{steps.pull-backup.outputs.artifacts.data}}"
    - - name: consumer
        template: influxdb-client
        arguments:
          parameters:
            - name: cmd
              value: curl --silent -G http://{{steps.influx.ip}}:8086/query?pretty=true --data-urlencode "db=mydb" --data-urlencode "q=SELECT * FROM cpu"
  - name: influxdb-client
    inputs:
      parameters:
        - name: cmd
    container:
      image: appropriate/curl:latest
      command: [ "sh", "-c" ]
      args: [ "{{inputs.parameters.cmd}}" ]

  - name: restore-backup
    inputs:
      artifacts:
        - name: data
          path: /opt
      parameters:
        - name: ip
    container:
      image: influxdb:1.8
      command: [ "/bin/bash","-c" ]
      args: ["influxd restore -portable -db mydb -host {{inputs.parameters.ip}}:8088 /opt"]
  - name: pull-backup
    outputs:
      artifacts:
        - name: data
          path: /opt
    container:
      image: paperhive/gcloud-tools
      command: [ "bash","-c" ]
      args: ["cd /opt;gsutil cp gs://{{workflow.parameters.bucket}}/{{workflow.parameters.bucket-path}}/mydb.tar.gz ./;tar xf mydb.tar.gz;rm -rf mydb.tar.gz"]
  - name: influxdb
    daemon: true
    container:
      image: influxdb:1.8
      env:
        - name: INFLUXDB_BIND_ADDRESS
          value: ":8088"
      ports:
        - name: influxdb-8086
          containerPort: 8086
          protocol: TCP
        - name: influxdb-8088
          containerPort: 8088
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /ping
          port: 8086
        initialDelaySeconds: 5
        timeoutSeconds: 1
