apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - logging-extensions.banzaicloud.io_eventtailers.yaml
  - logging-extensions.banzaicloud.io_hosttailers.yaml
  - logging.banzaicloud.io_clusterflows.yaml
  - logging.banzaicloud.io_clusteroutputs.yaml
  - logging.banzaicloud.io_flows.yaml
  - logging.banzaicloud.io_fluentbitagents.yaml
  - logging.banzaicloud.io_loggings.yaml
  - logging.banzaicloud.io_nodeagents.yaml
  - logging.banzaicloud.io_outputs.yaml
  - logging.banzaicloud.io_syslogngclusterflows.yaml
  - logging.banzaicloud.io_syslogngclusteroutputs.yaml
  - logging.banzaicloud.io_syslogngflows.yaml
  - logging.banzaicloud.io_syslogngoutputs.yaml
